### ISSUE TITLE
Question about asynchronous

### ISSUE THREAD

**Issue by ntl92bk** [mohsansaleem/Idle-Miner#1]
Hello,
I am researching the architecture fo unity project and yours is great for me to learn, but I have a question. 
For asynchronous, why would you use the Promise library instead of build-in async await or library like UniTask. Is that any better?

Thank you

**Comment by mohsansaleem** [comment]
Managing Promises was easy and we can perform chaining easily through promises. Keeping in view the Signal and command structure Promises fits right in. UniTask is a good suggestion given the memory benefits.

**Comment by ntl92bk** [comment]
Thank you for answer
